### ISSUE TITLE
请问如何运行？

### ISSUE THREAD

**Issue by LoveTaytay** [llluo/crossModalRetrieval#3]
您提供的服务器失效了，请问该如何运行呢？

**Comment by congjianluo** [comment]
您好，README.md中并没有提供在线服务器来进行系统的demo展示。如果您需要在自己的机器上运行的话，需要先下载Google Driver中的数据集文件、数据库的db、vgg的预训练权重放置在所需的路径下。然后运行`python app.py`，服务会跑在0.0.0.0:3000端口上，您可以通过访问机器IP:3000来访问到服务；如果是本机，则可以通过localhost:3000来访问服务。
