### ISSUE TITLE
帮助

### ISSUE THREAD

**Issue by dujinfeng** [llluo/crossModalRetrieval#4]
可以发一下配置环境的版本吗？非常感谢你的帮助

**Comment by congjianluo** [comment]
很抱歉因为我更换了电脑，所以暂时找不到对应的环境配置了。项目主要依赖的是Flask和TensorFlow，可能版本号比现在的版本低很多，如果运行时有什么报错可以在搜索引擎上进行检索。

**Comment by dujinfeng** [comment]
好的，感谢你的帮助




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "congjianluo/crossModalRetrieval"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月13日(星期二) 下午4:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [congjianluo/crossModalRetrieval] 帮助 (#4)





 
很抱歉因为我更换了电脑，所以暂时找不到对应的环境配置了。项目主要依赖的是Flask和TensorFlow，可能版本号比现在的版本低很多，如果运行时有什么报错可以在搜索引擎上进行检索。

**Comment by congjianluo** [comment]
谢谢如果有任何其他问题，欢迎继续提交issue。
